# -*- coding: utf-8 -*-
#
# SPDX-License-Identifier: Apache-2.0

import re
import sys
from os.path import abspath, dirname, join

import sphinx_material

sys.path.insert(0, abspath(".."))

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.coverage",
    "sphinx-mathjax-offline",
    "sphinx.ext.napoleon",  # before sphinx_autodoc_typehints
    "sphinx_autodoc_typehints",
]

# List of modules to be mocked up.
autodoc_mock_imports = []

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# The suffix(es) of source filenames.
source_suffix = {".rst": "restructuredtext"}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "qpmpc_layers"
copyright = "2022-2025 Stéphane Caron and the qpmpc contributors"
author = "Stéphane Caron"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# The short X.Y version.
version = None

# The full version, including alpha/beta/rc tags.
release = None

# Read version info directly from the module's __init__.py
init_path = join(dirname(dirname(str(abspath(__file__)))), "qpmpc_layers")
with open(f"{init_path}/__init__.py", "r") as fh:
    for line in fh:
        match = re.match('__version__ = "((\\d.\\d).\\d)[a-z0-9\\-]*".*', line)
        if match is not None:
            release = match.group(1)
            version = match.group(2)
            break

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also affects `html_static_path` and `html_extra_path`.
exclude_patterns = ["build", "Thumbs.db", ".DS_Store"]

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# "Show Source" link in the right-hand side bar
html_show_sourcelink = False

html_sidebars = {
    "**": [
        "logo-text.html",
        "globaltoc.html",
        "localtoc.html",
        "searchbox.html",
    ]
}

# The theme to use for HTML and HTML Help pages.
html_theme = "sphinx_material"

# Set link name generated in the top bar.
html_title = "qpmpc_layers"

# Theme options are theme-specific.
html_theme_options = {
    "color_primary": "green",
    "color_accent": "cyan",
    "globaltoc_depth": 1,
    "localtoc_label_text": "Contents",
    "nav_links": [
        {"href": "index", "internal": True, "title": "Index"},
        {"href": "module", "internal": True, "title": "Module"},
        {"href": "usage", "internal": True, "title": "Usage"},
    ],
    "repo_url": "https://github.com/stephane-caron/qpmpc/",
    "repo_name": "qpmpc",
}

# Fixes the warning "cannot cache unpickable configuration value"
html_context = sphinx_material.get_html_context()
